export const UserType = {
  CREATE_USER: 'CREATE_USER',
  FETCH_USERS: 'FETCH_USERS'
};

export const TaskType = {
  CREATE_TASK: 'CREATE_TASK',
  FETCH_TASKS: 'FETCH_TASKS'
};

export const OrderType = {
  FETCH_ORDERS: 'FETCH_ORDERS',
  ORDER_CREATED_WITH_CHECKSUMHASH: 'ORDER_CREATED_WITH_CHECKSUMHASH'
};
